import { GlobalStyle } from "../Styles/GlobalStyle";
import Head from "next/head";
import { Header } from "../Containers/Header/Header";

import "@fortawesome/fontawesome-svg-core/styles.css"; // import Font Awesome CSS
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically since it's being imported above

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Viessmann</title>
        <link
          rel="shortcut icon"
          href="https://viessmann.vercel.app/images/favicon.ico"
        />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <GlobalStyle />
      <Component {...pageProps} />
    </>
  );
}
